version: '3'

services:
  nginx1:
    image: nginx
    ports:
      - "8001:80"
    volumes:
      - /home/kali/Desktop/scripts/Docker/nginx/nginx1.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php1
    networks:
      - app-network

  nginx2:
    image: nginx
    ports:
      - "8002:80"
    volumes:
      - /home/kali/Desktop/scripts/Docker/nginx/nginx2.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php2
    networks:
      - app-network

  php1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network

  php2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

